package:
    name: metastock2pd
    version: 1.0.2

source:
    path: ../src
	
build:
    include_recipe: False
    number: 0
    noarch: python

requirements:
    build:
        - pandas        >=1.1.0
    run:
        - pandas        >=1.1.0

about:
    home: https://github.com/gityoav/metastock2pd
    license: GNU